### ISSUE TITLE
Requested enhancements for the reportpage

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#10]
1. Warnings for the batch are not present on the report page (important to add).
2. Coloring scheme  is different in the "analysis view" and report page?
3. The squares for previous samples with aberrations in the NCVX/Y graph are a bit big. Better to use the same size as in the T13-21 graphs?
4. Spellingerror, trsholds
5. Could we add a comment field for the whole batch that is also present on the reportpage. I think we disussed this but for some reason skipped it? This would be valuable for tracking batch related issues, e.g. low library yield, reruns etc.

**Comment by mayabrandi** [comment]
1-4) Fixed
5) This could be done but need an update of the database. Nothing we will prioritize now. Please open a separate issue for this.

Best,

Maya
