### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#109]
Hello!

We cannot reach the FF and CovX vs CovY pages for batch 1864188_358541. We get an "Internal Server Error" message. Can you look into this, please?

Ellika

**Comment by mayabrandi** [comment]
Absolutely!

Ill get back to you as soon as I know the reason.

/Maya

**Comment by ellikasahlin** [comment]
Good morning!

Any news on this issue?

Ellika




Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 9 oktober 2018 10:33
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Ellika Sahlin <ellika.sahlin@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#109)

Absolutely!

Ill get back to you as soon as I know the reason.

/Maya

**Comment by mayabrandi** [comment]
Im looking at it right now. Reason is some data is missing in the database for one of the samples. Ill update the code for the viewer so that it will exclude samples with missing data. Ill let you know when its in place.

**Comment by ellikasahlin** [comment]
Great, thanks!
/E



Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 10 oktober 2018 08:46
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Ellika Sahlin <ellika.sahlin@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#109)

Im looking at it right now. Reason is some data is missing in the database for one of the samples. Ill update the code for the viewer so that it will exclude samples with missing data. Ill let you know when its in place.

**Comment by mayabrandi** [comment]
Okej. Problem solved!

You will still have internal server error when trying to enter the ”empty” sample. That should be fixed in a prettier way. So lets keep this issue opened until I have time to work on the NIPT viewer finish.

/M

**Comment by ellikasahlin** [comment]
Super, thanks!
/E


Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 10 oktober 2018 09:05
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Ellika Sahlin <ellika.sahlin@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#109)

Okej. Problem solved!

You will still have internal server error when trying to enter the ”empty” sample. That should be fixed in a prettier way. So lets keep this issue opened until I have time to work on the NIPT viewer finish.

/M
