### ISSUE TITLE
Minor issues/corrections

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#11]
1. Spelling error on the first page, College instead of Colleague
2. It is not possible to use the search field on the first page for sampleIDs. Please change or add text that makes this clear
3. Please use T13 and not T_13 (the same for all) in all places.
4. Batch Warnings is misspelled, reads Warnins
5. Go over color scheme for suspected to verified (to similar for T13-T21) and I guess the general recommendation is not to use green and red in the same graph?

**Comment by mayabrandi** [comment]
1) Fixed
2) Are you sure you want this? The logic is that you can search the columns. Since there is no sample column, you can not search for samples in that table.
4) Fixed
5) Is the issue that you want the same color for verified, suspected, etc,  in the XY graphs, as in the 13,18,21 graphs? I can fix that if you want. 

I can not exclude green and red from the XY graph since it needs at least 21 different colors. 15 samples + verif, susp, prob, other, fp, fn.  25 to be on the safe side, if we have more samples in the batch. If you want 25 colors that are diferent and not red and green, Ill have to ask you to give me the list of color codes that you want, as we discussed in june.  @alieden

**Comment by mayabrandi** [comment]
5) I now updated so that its the same color for verified, suspected, etc, in the XY graphs, as in the 13,18,21 graphs

Can this issue be closed now?

**Comment by alieden** [comment]
As pointed out in nr 3 I would really like if we could change T_13 to T13 and the same for all the places where NCV or T is followed by _  or space to be consistent also. For example NCV_X to NCVX, T 21/T_21 to T21 etc. This is not a acute.

Regarding point 5 my suggestion (for the next update) would be to that we for all previously analyzed samples use symbols/figures instead of colors and only use colors for current batch/samples. I think this was in the summary pdf I sent but perhaps not in any ticket?

**Comment by mayabrandi** [comment]
Could you go over all plots now @alieden? I have not changed from colors to symbols, but otherwise I think ive done what you asked for. Please let me now if you are happy with the plots layout for now, or if there still are things you want me to change for this upgrade of the tool.

**Comment by alieden** [comment]
Yes, will do asap

Agne

21 nov. 2016 kl. 15:55 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:


Could you go over all plots now @alieden<https://github.com/alieden>? I have not changed from colors to symbols, but otherwise I think ive done what you asked for. Please let me now if you are happy with the plots layout for now, or if there still are things you want me to change for this upgrade of the tool.

**Comment by alieden** [comment]
The batches are not loading.
![batch not loading](https://cloud.githubusercontent.com/assets/22740092/20514109/7809f286-b08a-11e6-8459-1867c1e8168f.png)

**Comment by mayabrandi** [comment]
Ill look into it right now.

**Comment by mayabrandi** [comment]
Okej. Its upp again. But Ill open a separate ticket on the issue and ask @ingkebil to look into what could be the reason. This has happened before and all I did to fix it was to restart the program.

**Comment by alieden** [comment]
For the thresholds T13, T18 and T21 I would like it better if you just put NCV=3 and so on i.e. don't label with threshold or warning threshold. This is mostly because I can't think of any labels I like and if you just put NCV=3 that should be enough I think?

**Comment by mayabrandi** [comment]
Sure.

Vänligen,
Maya Brandi

**Comment by alieden** [comment]
For the NCVXY plot I would prefer something like what is shown in figure below. The labels could be inside our outside the axis depending on what is the easiest? For the XY samples I think a textbox explaining is also necessary. 

![ncvxy](https://cloud.githubusercontent.com/assets/22740092/20522622/97fc315e-b0b1-11e6-83a1-551481662f02.png)

**Comment by alieden** [comment]
The values for the prediction interval should be as in the fig below. Please not that the 5 SD lines are actually not perfectly parallel as you would expect in a confidence interval if I remember correctly. Perhaps there was some reason why we decided to draw them parallel, I will go through my previous emails and check if I find anything.

![rikningskoeff](https://cloud.githubusercontent.com/assets/22740092/20522705/fc35d706-b0b1-11e6-8cd2-9a76abd92436.png)

**Comment by mayabrandi** [comment]
Hej. Sorry. My mistake. I am using those equations to generate the lines, so they are not parralell. I just made the line label wrong. Fixed now on the [development channel](https://clinical-db.scilifelab.se:7072/NIPT). Will push to production later today.
