### ISSUE TITLE
Negative nr are incorrect

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#12]
The negative nr are the same in all graphs which is incorrect. Negative is only in relation to the specific analyte e.g. T21. 

This becomes a bit problematic for the NCVXY data/graph and I think we could be happy with just the normal XX and XY being represented as negative in this case i.e. not divide into the different sex chromosome aneuploidy groups. From the table you could fairly easily figure out what nr of samples are negative for XXY e.g.

**Comment by mayabrandi** [comment]
Hej hej!

Ledsen, men det är oklart för mig vad du menar här. Om vi tar T21 som exempel. Exakt vilka prover är det du vill ska vara "Negative"? Vill du inte att "Negativ" ska vara NCV-fördelningen av alla godkända prover, och därmed visa det som är normalt?


/Maya

**Comment by alieden** [comment]
För T21 ska negative vara alla de prover som har NCV21 mindre än 3,0 och dessutom har blivit checked för att vara inkluderade (då det finns dubletter, omkröningar etc). Det blir sedan likadant för T13 och T18 vilket leder till att antalet negative borde vara störst för T13 (ovanligast) och minst för T21 (vanligast). Med andra ord tar man bara hänsyn till en analyt åt gången. Hoppas det blev tydligare nu?

Ett problem är dock hanteringen av könskromosomavvikelser men efter lite fundering kanske man kan slopa negative i den tabellen och bara ha med alla grupperna dvs negative delas upp på XY och XX så får man den informationen också. Går det bra?

**Comment by mayabrandi** [comment]
Okej. Förstår vad du menar nu. Ska se om denna ändring blir klar till denna versions-uppdatering, eller till nästa.

**Comment by alieden** [comment]
Tack! En generell kommentar i anslutning till detta skulle vara att det förstås är mer prio med att rätt data visas och att vi kan få till en hyfsat snygg rapport jmfr med mindre ändringar i färger etc.  

Om det ser konstigt ut avseende data kommer det bli en massa onödig osäkerhet på vår sida. Detta då det nu är läkarna som besvarar NIPT (rullande schema så det är ofta nya som kommer etc) analyserna och dom kommer bara titta på resultatet som den pdf från systemet som bifogas.

**Comment by mayabrandi** [comment]
Okej, jag är med. Försöker fixa denna asap. Detta kommer även lösa förvirringen i issue #30. Så jag stänger den issuen nu så att vi inte har dubletter.

**Comment by mayabrandi** [comment]
Vill bara dubbelkolla så att det blir rätt.. För tex T13: 

Negative **ska inte vara** alla som är klassade som "Normal" T13.

Negative **ska vara** alla som har NCV13 < 4 (den övre röda linjen i grafen). Om ett prov har NCV13 < -4 så är det fortf Negative?


Korrekt?

**Comment by alieden** [comment]
Gränsen är 3,0 för T13 (och T18 och T21).

Negative för T13 blir de prover som har NCV-värde under 3,0 gränsen (för T13 och utan att ta hänsyn till andra analyter) och dessutom klickats i för att vara inkluderade.

Jag tänker att det borde bli samma resultat om du använder de som fått ”Normal” T13 (för det är väl förvalt?) eller om du använder 3,0 gränsen? Kan man testa detta enkelt som en kontroll? Möjligen skulle man kunna tänka sig att vi kanske ändrar gränser längre fram och då skulle det väl vara fördelaktigt att ha valt ”Normal” status/klassificering som avgörande? Kanske enklast att använda det om du inte kommer på någon anledning till att istället använda värdet?




Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 14 november 2016 08:29
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] Negative nr are incorrect (#12)


Vill bara dubbelkolla så att det blir rätt.. För tex T13:

Negative ska inte vara alla som är klassade som "Normal" T13.

Negative ska vara alla som har NCV13 < 4 (den övre röda linjen i grafen). Om ett prov har NCV13 < -4 så är det fortf Negative?

Korrekt?

**Comment by mayabrandi** [comment]
Okej. Nej det är inte samma sak. Normal, Verified, False Positive, False negative, etc är de klasser som ni sätter manuellt. Ni kan alltså välja att sätta Normal på ett prov som har ett NCV värde > 3, men som ni av någon anledning kommit fram till inte är en trisomi.

**Comment by alieden** [comment]
Ok. Men ”Normal” är den förvalda klassen som används om man inte ändrar manuellt?

Vi kommer inte sätta ”Normal” för de som ligger över 3,0.
Möjligen skulle man kunna göra det om vi ändrar gränsen senare men då får man väl omklassificera de proverna alternativt hitta på någon ”gränsvärde” klassificering för de som hamnar mellan den gamla och den nya gränsen.

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 14 november 2016 10:48
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] Negative nr are incorrect (#12)


Okej. Nej det är inte samma sak. Normal, Verified, False Positive, False negative, etc är de klasser som ni sätter manuellt. Ni kan alltså välja att sätta Normal på ett prov som har ett NCV värde > 3, men som ni av någon anledning kommit fram till inte är en trisomi.

**Comment by mayabrandi** [comment]
Toppen. Då plottrar jag bara normal prover son ”Negative”. Fixar senare idag.

/Maya

**Comment by mayabrandi** [comment]
Så. Fixat. 

I NCV_XY plotten är Negative samples helt enkelt de som är Normal klassade map. XXX, XXY, XYY, **och** X0 samtidigt. Blir det bra?

I NCV_13 plotten är Negative samples de som är Normal klassade map. NCV_13.

Samma för NCV_18 och NCV_21 som för NCV_13

Ok? Kan denna stängas nu?

Vänligen,

Maya

**Comment by alieden** [comment]
Nu börjar det se riktigt bra ut!

Mitt förslag var tidigare i tråden att vi skulle skippa negative i XY plotten dvs dela upp dom på XY och XX så har man all information. Det är ju trevligt att se att ratiot mellan kön är det förväntade. Är det knepigt så kan det vänta till nästa version. 

Summeringen av T13, T18 och T21 blir 1991 st (utan psc) för alla så det ser rätt ut. Sen stämmer det inte med att det i sample list står att det ska vara 2000 prover men jag måste fundera över varför det blir så.

**Comment by alieden** [comment]
Summeringen för XY grafen blir 1987 om man inkluderar batchen man tittar på (utan pcs). Måste fundera lite över det också.

**Comment by mayabrandi** [comment]
Jag förstår inte vad du menar med summeringen för XY grafen eller summeringen av T13, T18 och T21.

**Comment by alieden** [comment]
Jag menar att antalet negative + false positive + verified + suspected + probable borde bli samma summa i alla plottar. Denna summa borde också vara lika med det totala antalet prov som man klickat i för att inkludera? Eller tänker jag fel? Jag är för trött för att tänka mer nu, ska ladda ner databasen imorgon och se om man från den kan bli klok på vad det är för prover som är inkluderade men inte med i plottarna? Kanske något prov som blivit felklassat? Vad händer med de som blir klassade som "other" t ex?

**Comment by mayabrandi** [comment]
Du måste skriva ut sådana saker tydligt. Jag är inte bra på att läsa mellan rader och vi har inte tid med att jag ska gissa vad du menar. Imorgon är beräknad födsel :)

Men toppen! Du upptäckte en bugg. I antalet verifiied, suspected, etc. i XY plottens header lista, var icke-inkluderade prover medräknade, även om de inte var med i själva plotten. Förstår du hur jag menar? Ändrat det nu. Jättebra om du kontrollräknar igen! 

Prover som klassats som Failed inte är med i plottarna (enligt er önskan). Så därför kommer inte summan av alla prover i en plott vara samma som totalt antal inkluderade prover.

**Comment by alieden** [comment]
Ok. Det ligger fortfarande en "negative dot" i XY-ploten, markerad med röd pil i bilden nedan
![xy_plot_negative](https://cloud.githubusercontent.com/assets/22740092/20299722/659ade76-ab1c-11e6-92a1-56db7cd61073.png)

**Comment by mayabrandi** [comment]
Ja jag såg det. Något prov som ni glömt att klassificera. Skulle du vilja kunna hoovra över Negative samples också? Så att du kan se vad det är för prover. Tror vi tog bort hoovringsfunktionen på dom för att det kändes rörigt, men det är lätt att ta tillbaka.

**Comment by alieden** [comment]
Jag tror vi avvaktar med att ändra, som sagt blir det nog rörigt.

Lyckades hitta vilket prov det var, en omkörning som inkluderats av misstag

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 15 november 2016 10:52
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] Negative nr are incorrect (#12)


Ja jag såg det. Något prov som ni glömt att klassificera. Skulle du vilja kunna hoovra över Negative samples också? Så att du kan se vad det är för prover. Tror vi tog bort hoovringsfunktionen på dom för att det kändes rörigt, men det är lätt att ta tillbaka.

**Comment by mayabrandi** [comment]
Ska jag stänga denna issue nu?

mvh,

Maya

**Comment by alieden** [comment]
Ja det går bra för mig

Agne

15 nov. 2016 kl. 16:19 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:


Ska jag stänga denna issue nu?

mvh,

Maya
