### ISSUE TITLE
Adjust to new csv input file

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/NIPT#121]
Jesper is developing a new NIPT pipeline and the NIPT viewer needs to be adjusted to the new output csv.

**Comment by mayabrandi** [comment]
Anteckningar från möte med Agne och Jesper

**Hur hantera att vi inte har någon NCV_Y data?**

- [x] Plott NCVXY:   FFY mot FFX - ta bort gränserna. 
- [x] Plott NCVXY:   (Om det inte är krångligt byt pol på x axeln.) 


- [x] Plott FF: lägg in FF mot FFY i en plott

- [x] Plott FF: lägg in FF mot FFX i en annan plott.

- [x] Coverage (CHR 1-22) byt namn till ratio

- [x] NCV tabellen: ta bort NCVY

- [x] NCV tabellen: lägg till FFX och FFY - ignorera varningar. 

- [x]  NCV tabellen: lägg till kolumn CNVSegment - om det står Found 
- [ ]  NCV tabellen - CNVSegment: lägg in en läk till filen med segmental calls.   

- [x] XY-plot på provnivå kan ryka. 121821 kan finnas kvar

- [x] QC- fliken. ta bort alla gränsvärden.

![Skärmavbild 2020-03-23 kl  13 27 19](https://user-images.githubusercontent.com/1306333/77318411-4fdb5c80-6d0d-11ea-9655-ecef9e404903.png)


**hur hantera de nya kolumnerna index1, index2, indexID1 och indexID2?**

- bort med gamla index. In med nya.

**Comment by henrikstranneheim** [comment]
@mayabrandi If this is done - is it okey to close?

**Comment by mayabrandi** [comment]
Yes. Ill close it
