### ISSUE TITLE
Error in sequencing date?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#17]
There are a nr of validation batches with sequencing date before april 2015. This is probably incorrect?

**Comment by mayabrandi** [comment]
@ingkebil , can you look into this one when you have time? Ive just imported everything that was in the analysis_results directory in the begining of june. Could it be the case that some batches were marked with the wrong date? 

Best,

Maya

**Comment by ingkebil** [comment]
`140220 	AH8P5EADXX`: This is the test flowcell from Illumina.
`140929 	AH143RBGXX`: Test flowcell for upgrade of NIPT server of 12th May.

These can be safely ignored. We will remove them.
