### ISSUE TITLE
NCV-graferna fungerar inte

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#2]
Hej!

Graferna för NCV_13, NCV_18 och NCV_21 fungerar inte. Det blir bara en vit ruta. Se screenshot!

![screenshotnipt](https://cloud.githubusercontent.com/assets/18735539/14912415/77638238-0dfc-11e6-97be-23ab66fddbc7.png)

Ellika

**Comment by mayabrandi** [comment]
Hej!

Det är fixat nu. Blev en följd av buggfixen jag gjorde igår. Förhoppningsvis ska det stabilisera sig snart så att ni inte får massa buggar, men det är bra att ni använder verktyget så att ni kan upptäcka.

Ledsen för strul.

Mvh,

Maya
