### ISSUE TITLE
Missing data 150630

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#20]

**Comment by mayabrandi** [comment]
Hej hej!

Är det inte denna batch? https://clinical-db.scilifelab.se:8082/NIPT/batches/AHNTYHADXX/


Vänligen,

Maya

**Comment by mayabrandi** [comment]
Kan jag stänga denna issue Agne?

**Comment by alieden** [comment]
Jo det är den batchen men det är ju för få prover som visas av någon anledning, bifogar resultatfilen. 
[results_20150626_505852_HNTYHADXX.zip](https://github.com/Clinical-Genomics/NIPT/files/587687/results_20150626_505852_HNTYHADXX.zip)

**Comment by alieden** [comment]
Det här dock inte prioriterat att fixa då det handlar om valideringskörningarna och inte det kliniska. Mao kan det fixas längre fram.

**Comment by mayabrandi** [comment]
Ok, jag har identifierat problemet och uppdaterat denna körning. Ska göra det för de andra tre också. Dock behöver vi gå igenom batcher med omkörda prover för att kolla om dom kommit in som dom ska. Jag är rädd att omkörda prover exluderats för flera batcher. :((( Har du något sätt att få fram lista på omkörda prover enkelt?
