### ISSUE TITLE
bug - not possible to download the database

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#23]
Trying to download the database but I just get the webpage can't be shown message. This function is important since I wan't to be able to compare the data with other files for the validation.

**Comment by alieden** [comment]
I can now download the database as a csv file but if I import the data (as comma separated) into excel I get something that looks a bit odd? From the way it looks I would assume there are some sorting issues but I haven't looked at the data in more detail. Should I do something else?

[xls_NIPT_db.xlsx](https://github.com/Clinical-Genomics/NIPT/files/547232/xls_NIPT_db.xlsx)

**Comment by mayabrandi** [comment]
Hej!

Specificera gärna problemet med filen lite mer! Lite oklart för mig vad som är problemet.

Vänligen,

Maya

**Comment by alieden** [comment]
Har gulat några konstigheter i bifogade filen men det finns gott om dom så det går inte att markera allt etc. Kontrollera kolumnerna mer till höger I filen. Orsakas detta av något vid omvandligen från cvs till xls dvs vid import av textfilen till excel? Får du samma resultat? 



[xls_NIPT_db_gulad.xlsx](https://github.com/Clinical-Genomics/NIPT/files/582834/xls_NIPT_db_gulad.xlsx)

**Comment by mayabrandi** [comment]
De exempel du markerat är prover som skapats av den sista raden i vissa av analys resutlat filerna. Filen innehåller exakt den data som fins i databasen vilket den ju ska göra. Men sen att det kommit in sådana där felaktiga prover i databasen är ju inte meningen. Detta problem behandlas i issue #14 

Är det något annat du undrar över gällande databas-dumpen? Eller kan vi stänga denna issue nu? @alieden

**Comment by alieden** [comment]
Jag får titta på det igen när felaktiga prover justerats så det går att stänga denna issue

**Comment by mayabrandi** [comment]
👍
