### ISSUE TITLE
NIPT batch report printing, furter testing

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#31]
I have now been in contact with the IT department and we have tested some different settings regarding the pdf print-out. It appears that using IE (v11) and 50% reduction gives a report that looks ok-ish (attached), I will post some suggestions (as separate issues) for minor enhancements. Firefox and pdf-print-out has problems with the table formats for some reason (comes out as cropped or moved). As we have discussed before, and gave up for some reason, they of course think that it would be best if there was a pdf creator button in the analysis tool so that you can be sure that the report always looks the same. When you move to individual clients and have to rely on the settings being the same to avoid losing info etc it is of course a bit more complicated and risky. Perhaps we would be able to create a specific pdf creator on our side but we will see what is feasible. Do you think this batch is representative or could there be cases were there are more columns in the tables etc meaning that you have the risk of losing info?

[NIPT_Batch_report_IE11_50_percent_test.pdf](https://github.com/Clinical-Genomics/NIPT/files/589301/NIPT_Batch_report_IE11_50_percent_test.pdf)

**Comment by vwirta** [comment]
If there is a working solution at the moment, then I suggest we link further improvements to version 2.2

**Comment by vwirta** [comment]
Agne, just checking... can you see linked milestone + label on this ticket?

**Comment by alieden** [comment]
Yes I see them but when I create a new ticket I still don't see that I have an option to add labels like in Mayas picture but perhaps I'm doing something wrong.

**Comment by alieden** [comment]
I think this can be closed for now.
