### ISSUE TITLE
Batch page - missing data header?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#33]
Maya, could you please remind me what the column labelled with Missing data is for? How does it work?

![1630555](https://cloud.githubusercontent.com/assets/22740092/20283668/3906f050-aaba-11e6-921a-641780e6de94.png)

**Comment by mayabrandi** [comment]
HI!

If NonExcludedSites < 8000000, Missing Data will be populated with NonExcludedSites. 

NonExcludedSites comes from the nipt analysis result file.

**Comment by alieden** [comment]
Ok. Since the header is not self-explanatory perhaps you could add a text explaining this but leave it for the next version

**Comment by mayabrandi** [comment]
👍

**Comment by mayabrandi** [comment]
I added a "hover comment" for that column in the batch page. Can you see if you are happy with that? Also, do you want comments for the "QC-warnings" table in the report page, that explains all columns? Could you wright those comments for me in that case, so we get them right from start? @alieden 

/M

**Comment by alieden** [comment]
I’m happy with that! The other are sort of self-explanatory I think so let’s leave it for now.

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 21 november 2016 10:29
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Mention
Ämne: Re: [Clinical-Genomics/NIPT] Batch page - missing data header? (#33)


I added a "hover comment" for that column in the batch page. Can you see if you are happy with that? Also, do you want comments for the "QC-warnings" table in the report page, that explains all columns? Could you wright those comments for me in that case, so we get them right from start? @alieden<https://github.com/alieden>

/M
