### ISSUE TITLE
Kommer ej in på senaste batchen

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#4]
Hej! 
Det går inte att komma in på den senaste batchen (1622448_891743, date 160511). Vi har haft detta problem tidigare. "Internal Server Error" står det.

Ciao! 
Ellika

**Comment by ellikasahlin** [comment]
Kan ni bekräfta att ni sett detta? Det går fortfarande inte att komma in på batchen.

**Comment by mayabrandi** [comment]
Goddagens.

Jag ser detta. Det har med den failade körningen att göra. Jag ska skriva om koden så att det går att lösa denna typ av problem snabbt ock enkelt framöver. Återkommer när det är klart!


Mvh,

Maya

**Comment by mayabrandi** [comment]
Goddagens.

Jag ser detta. Det har med den failade körningen att göra. Jag ska skriva om koden öide så att det går att lösa denna typ av problem snabbt ock enkelt framöver. Återkommer när det är klart!


Mvh,

Maya

**Comment by mayabrandi** [comment]
Nu är det lagat!

/M

**Comment by vwirta** [comment]
Kanon!

VW

> On 16 maj 2016, at 17:55, mayabrandi <notifications@github.com> wrote:
> 
> Nu är det lagat!
> 
> /M
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/NIPT/issues/4#issuecomment-219463470>

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna
