### ISSUE TITLE
Enhancement of the plots regarding "other" aberrations

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#40]
For chromosome 13 we had a sample that gave a result below the threshold for monosomy 13 (marked with red arrow below). The result was as expected a false positive and it is now shown as a false positive T13 which is a bit less than optimal but not a big thing. I tried changing it to status "other" for T13 but it is then not shown in the plot. 
Although not a perfect solution, perhaps a quick fix for this would be to change so that the status "other" also is shown in the plot so that we can keep track of these kind of samples? Would that be easy to do for all plots Maya?

![monosomi_13](https://cloud.githubusercontent.com/assets/22740092/20304859/bc58776c-ab32-11e6-87aa-62793f0530a2.png)

**Comment by mayabrandi** [comment]
Yes! Ill fix that!

Vänligen,
Maya Brandi

**Comment by alieden** [comment]
Thank you!

**Comment by mayabrandi** [comment]
Fixed
