### ISSUE TITLE
Issue regarding database file (enhancement)

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#41]
Hi everyone!
Finally I’m back in the clinical work after a period of focusing on my research and dissertation! (For your information I will work full time at Clinical genetics from now on.)

I have understood that our timing for evaluation of the analysis tool is very far from optimal… I apologize that I have not been clear about that I haven’t been working in the clinic for quite a long time. But most of all I would like to say CONGRATULATIONS to Maya! :)

Now to the issue, regarding the database file (I’ve tried to make it super clear, sorry if it just sounds silly).
1. The file is comma separated, so when I open it in Excel I separate the data at each comma so that it ends up in separate cells. However, some data is already separated, which means that it will be overwritten when I do the separation. I looked at the file in Notepad, and it seems like some of the data is separated by semicolon instead of comma. Can you possibly look into this? 

2. Is it possible to move the “Comments” section so that it is the last column in the file (i.e. the column farthest to the right)? As the file is comma separated, every time we use a comma in a comment, the subsequent data will be shifted to the right. Example: I have written the comment “Illumina sample, competency testing” for all our competency samples. In the database file this comment will be split into 2 cells because of the comma. Of course we could have as a policy to never use commas in our comments, but I suspect that mistakes will be made occasionally. If we could move the Comments column farthest to the right side we would at least not affect the rest of the data.

As you see I requested an “enhancement flag” on this issue. I cannot see the button in my web browser (I heard that Agne had the same problem). Hope that’s OK!
Thanks in advance!
Ellika

**Comment by mayabrandi** [comment]
Hi Elika! Welcome back! And thanks for congrats :)

I see. Im using a standard python tool to generate the csv file, so I was convinced the tool would be able to handle values containing commas, but obviously not. Im replacing ',' with '.' now. Before creating the csv. Think the problem is solved hereby.

Will you double check?

Best,

M

**Comment by ellikasahlin** [comment]
I would like to, but right now I can't open the analysis tool at all. The site is just loading and nothing happens!

**Comment by ellikasahlin** [comment]
Now it's working!

It seems like you solved it, thank you! Will the replacement be performed automatically each time we download the database?

However, issue 1 still remains, i.e. that there are semicolons in the file which will cause some cells to be overwritten.

**Comment by mayabrandi** [comment]
I cant see what you mean really. I see that there are some semicolons, but I cant see that things get over written because of that. I attach a screen shot... Could you maybe point me to an exact example in the file by attaching a new file here and give me the cell coordinates?

Best,

M
<img width="996" alt="skarmavbild 2016-11-18 kl 12 36 50" src="https://cloud.githubusercontent.com/assets/1306333/20428940/15d36c4c-ad8c-11e6-8d3b-d741dbd974da.png">

**Comment by ellikasahlin** [comment]
See attachment! Hope it's clear. 
[Database issue.pdf](https://github.com/Clinical-Genomics/NIPT/files/599982/Database.issue.pdf)

Kind regards,
E

**Comment by mayabrandi** [comment]
Okej. The problem probably is that the default setting of Microsoft Excell is to separate by semicolon? I Dont work with Microsoft, but I suppose that, if you want to read the csv through microsoft Excell, you start by opening the application, and then select import file and then choose coma separation. Thats how one would do it through google spred sheets at least, and they are pretty similar I think. Could you try that out and let me know if it works for you?


Best,

Maya

**Comment by ellikasahlin** [comment]
Ah, of course! It works now, thank you!

Have a nice weekend!
E

**Comment by mayabrandi** [comment]
:) You to!
