### ISSUE TITLE
Enhancement of XY-plot, the X0/XY samples

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#42]
As is evident from the XY plot we really have a group of samples that we were not really expecting, that is the XY samples showing lower X signal than expected (marked with arrows). Illumina apparently ignores if samples are deviating this way. These will probably almost always be explained by a small population of X0 cells in the mothers blood (normal variation). However, since X0/XY mosaicism in the fetus (and also some other aberrations) could give the same result we will have to continue to do follow-up for these samples. You could change the status for these to "other" to differentiate from "normal X0" samples without Y chromosome signal but then you loose the quick overview regarding follow-up information for these samples. I think the only solution would be to add another analyte called XO/XY? What do you think? Other suggestions?

![x0_xy_samples](https://cloud.githubusercontent.com/assets/22740092/20306335/02bcbea0-ab3a-11e6-995b-05c45617b0a3.png)

**Comment by mayabrandi** [comment]
This will require an upgrade of the database, and I therefor suggest we leave this to the next upgrade.

**Comment by alieden** [comment]
Ok

Agne

21 nov. 2016 kl. 15:57 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:


This will require an upgrade of the database, and I therefor suggest we leave this to the next upgrade.

**Comment by alieden** [comment]
I don't think this solution is reasonable anymore. We have since the introduction of fetal fraction stopped doing follow-up analysis if the Y-signal correlates with the fetal fraction estimate (excluding the X0/XY mosaicism possibility). What would be good is an easier way to see if the NVCY value is in agreement with the fetal fraction (at the moment we compare with a print-out of previous data from XY-samples that have also the fetal estimate) for these samples directly when they occur. We should discuss what is the best option in relation to other fetal fraction related graphs?
