### ISSUE TITLE
Enhancement for next version - fetal fraction

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#46]
While I have this in my head, since fetal fraction is now added to the result with the server upgrade this will of course be something that we want to add in the next version.

**Comment by mayabrandi** [comment]
Yep! 👍

**Comment by alieden** [comment]
Fetal fraction estimation has been included in the NIPT analysis server (fall 2016) and we currently fail samples with less than 2% ff. We need to add this analyte (like T13, T18 etc) in the viewer+report. Alternatively this could be added just as another column in the NCV table (and flagged if below 2%). What would be the easiest for you to implement? We also need to be able to follow this over time as for the QC-metric in the Statistics part of the viewer

**Comment by mayabrandi** [comment]
Now added FF to the batch table in the batch page. Here is an example. See if it is what you wanted.

https://clinical-db.scilifelab.se:8082/NIPT/batches/AH2YJ3ADXY/

**Comment by alieden** [comment]
Yes this looks good but I have to check what happens with the report i.e. if it becomes i problem when making a pdf I guess. When a sample fails a QC-metric this is usually also reported above the table if memory serves me right. Could this feature be added also for fetal fraction since it's sort of both an analyte and a QC-metric? Not very important. We should at least make the cells red in the table if below 2%.

________________________________
Från: mayabrandi [notifications@github.com]
Skickat: den 4 oktober 2017 15:30
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] Enhancement for next version - fetal fraction (#46)


Now added FF to the batch table in the batch page. Here is an example. See if it is what you wanted.

https://clinical-db.scilifelab.se:8082/NIPT/batches/AH2YJ3ADXY/

**Comment by mayabrandi** [comment]
@alieden Can you confirm that this issue is ready to be closed now?

**Comment by alieden** [comment]
Yes thank you!

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 07:46
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Enhancement for next version - fetal fraction (#46)


@alieden<https://github.com/alieden> Can you confirm that this issue is ready to be closed now?
