### ISSUE TITLE
Senaste batchen går ej att öppna.

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#5]
Hej! 
Nu har vi problem med att öppna ytterligare en batch: 1622776_129948, Date: 160518

Samma fel som förra gången, "Internal server error".

Hälsningar,
Ellika

**Comment by ingkebil** [comment]
Hi Ellika,

that run failed and there is bound to not be any good data in that run.
Do you want us to remove that batch?

wkr,
Kenny

**Comment by ellikasahlin** [comment]
OK, thanks for info!
I suppose that there will be data when you rerun the sequencing?
If the failed batch will stay in the system as a duplicate you can remove it!

Kind regards,
E

**Comment by vwirta** [comment]
I see that there are problems showing the run from yesterday as well. Probably due to naming conflict again - Maya needs to look into this.

The question is how should we handle the upload to db.
Should we define rules such that only ok runs are uploaded. If so, what is the trigger?

VW


> On 19 maj 2016, at 11:41, ellikasahlin <notifications@github.com> wrote:
> 
> OK, thanks for info! 
> I suppose that there will be data when you rerun the sequencing? 
> If the failed batch will stay in the system as a duplicate you can remove it! 
> 
> Kind regards, 
> E 
> 
> 
> 
> 
> 
> 
> 
> From: Kenny Billiau [mailto:notifications@github.com] 
> Sent: den 19 maj 2016 11:32 
> To: Clinical-Genomics/NIPT 
> Cc: Ellika Sahlin; Author 
> Subject: Re: [Clinical-Genomics/NIPT] Senaste batchen går ej att öppna. (#5) 
> 
> 
> Hi Ellika, 
> 
> that run failed and there is bound to not be any good data in that run. 
> Do you want us to remove that batch? 
> 
> wkr, 
> Kenny 
> 
> — 
> You are receiving this because you authored the thread. 
> Reply to this email directly or view it on GitHub<https://github.com/Clinical-Genomics/NIPT/issues/5#issuecomment-220274280> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/NIPT/issues/5#issuecomment-220276356>

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna

**Comment by ellikasahlin** [comment]
CC Agne.

I guess there is no point to upload runs that we cannot even open. Regarding the trigger – I don’t know..
Does Agne have any suggestions?

Ellika

**Comment by mayabrandi** [comment]
So the run 1622776_129948 <https://clinical-db.scilifelab.se:8082/NIPT/batches/AH272YADXY/> is now up on the website.

Ill find a solution for the issue so it won’t be happening in the future. 

/M


> 20 maj 2016 kl. 1:51 em skrev ellikasahlin <notifications@github.com>:
> 
> CC Agne. 
> 
> I guess there is no point to upload runs that we cannot even open. Regarding the trigger – I don’t know.. 
> Does Agne have any suggestions? 
> 
> Ellika 
> 
> 
> 
> From: Valtteri Wirta [mailto:notifications@github.com] 
> Sent: den 20 maj 2016 11:48 
> To: Clinical-Genomics/NIPT 
> Cc: Ellika Sahlin; Author 
> Subject: Re: [Clinical-Genomics/NIPT] Senaste batchen går ej att öppna. (#5) 
> 
> I see that there are problems showing the run from yesterday as well. Probably due to naming conflict again - Maya needs to look into this. 
> 
> The question is how should we handle the upload to db. 
> Should we define rules such that only ok runs are uploaded. If so, what is the trigger? 
> 
> VW 
> 
>
