### ISSUE TITLE
NIPT viewer not loading

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/NIPT#55]
It has now happened twice that the NIPT viewer is not loading. All I did to fix it was to restart it in supervisorctrl. Didn't figure out what caused the issue. (The problem has only occurred on the production port 8082. Never on the test port 7072.) If this happens again, please report it here @alieden. And it would be great if you could keep an eye on this issue @ingkebil. I think you are better at debugging this than I am.

**Comment by alieden** [comment]
Some added info on this might be that I was able to get to the first NIPT batches page but when clicking one of the batches you get the following message.

![batch not loading](https://cloud.githubusercontent.com/assets/22740092/20523281/947f0904-b0b4-11e6-854c-2f4e7c02199e.png)

However, after testing a bit I realized I was able to load the sample list and then get into the batches from there?

**Comment by alieden** [comment]
It is once again not possible to reach the batches from the first NIPT batches page. You can load the sample list but clicking on a link for a batch gives the same error as above.

**Comment by alieden** [comment]
It is not possible to download the database either, no response when clicking

**Comment by alieden** [comment]
It is once again not possible to reach the batches from the NIPT batches page.  Same in both firefox and internet explorer. Restart of computer and deleting browser history doesn't help.

**Comment by ingkebil** [comment]
I've restarted the server and the website is back up again. This will be solved when we switch from the website's internal webserver to a proper multithreaded webserver.

**Comment by alieden** [comment]
Thank you! 
I saw that there is an old ticket (462640) relating to this issue that could be closed if you like. Do you have any idea when the server might be in place?

**Comment by ingkebil** [comment]
I'll have a look at it this week. For now I'll restart the viewer every second hour.

**Comment by alieden** [comment]
Ok, thank you!

Agne

5 dec. 2016 kl. 21:47 skrev Kenny Billiau <notifications@github.com<mailto:notifications@github.com>>:


I'll have a look at it this week. For now I'll restart the viewer every second hour.

**Comment by ingkebil** [comment]
Continuing in #73
