### ISSUE TITLE
Missing data in statistics view? Bug?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#59]
There is a bug in the statistics part so that all/only batch is shown per sequencing date? We usually have two batches per sequencing date and need to be able to see each batch separately.

**Comment by mayabrandi** [comment]
I see. What we have now is actually the 20 most reacent dates when a batch was run, not the 20 most reacent batches. Showing the 20 most reacent batches will imply we show less than 20 dates back in time. That is what you want? Just want to double check!! 

/MB

**Comment by alieden** [comment]
Would it be a lot of work to adjust so that all batches (normally 40) from the 20 latest sequencing dates are visible? Perhaps this will look to “crowded”? In principle we want the time span (with all batches shown) to be as long as possible to see weak trends for all metrics over time but it should also fit nicely in one figure. Could you do some testing on what is feasible?

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 2 oktober 2017 09:46
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Missing data in statistics view? Bug? (#59)


I see. What we have now is actually the 20 most reacent dates when a batch was run, not the 20 most reacent batches. Showing the 20 most reacent batches will imply we show less than 20 dates back in time. That is what you want? Just want to double check!!

/MB

**Comment by mayabrandi** [comment]
Ill see what I can do. It will look very crowded for sure. But if we remove the legend I guess that would work. You can still see each bach name by swiping the mouse over it. Could that be a solution?

Best,

M

**Comment by alieden** [comment]
Would it be ok to change so that the batch sequencing date is replaced with the name of the batch (under the x-axis)?

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 2 oktober 2017 11:06
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Missing data in statistics view? Bug? (#59)

Ill see what I can do. It will look very crowded for sure. But if we remove the legend I guess that would work. You can still see each bach name by swiping the mouse over it. Could that be a solution?

Best,

M

**Comment by mayabrandi** [comment]
That is probably a good solution.

**Comment by mayabrandi** [comment]
Ok. Have a look here <https://clinical-db.scilifelab.se:7072/NIPT/statistics/> and see if you are ok with this. 

The following changes are done:
* All batches from the same date are shown. 
* Batch names instead of dates on the x axis.
* Legends are removed.
* The 40 most reacent batches are always shown. (A quicker, compromise solution to your suggestion to show all batches from the 20 latest sequencing dates.)

**Comment by alieden** [comment]
I get the message “can’t view this page”?


Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 3 oktober 2017 10:39
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Missing data in statistics view? Bug? (#59)

Ok. Have a look here <https://clinical-db.scilifelab.se:7072/NIPT/statistics/> and see if you are ok with this.

The following changes are done:
* All batches from the same date are shown.
* Batch names instead of dates on the x axis.
* Legends are removed.
* The 40 most reacent batches are always shown. (A quicker, compromise solution to your suggestion to show all batches from the 20 latest sequencing dates.)

**Comment by mayabrandi** [comment]
Okej. Don’t know why. Its a developers channel. Maybe you need some kind of access. I attach a screen shot. If you think it looks fine, ill push it to production.

**Comment by alieden** [comment]
Managed to get in now for some reason. I think this looks fine!

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 3 oktober 2017 12:20
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Missing data in statistics view? Bug? (#59)

Okej. Don’t know why. Its a developers channel. Maybe you need some kind of access. I attach a screen shot. If you think it looks fine, ill push it to production.
