### ISSUE TITLE
Adjust prediction levels in the graphs

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/NIPT#61]
@alieden , I make a separate issue for this. You wrote the following in a mail to Valtteri: 

"There is a labeling of thresholds and equations for the prediction level shown in the graphs that we would like to have adjusted, alternatively just remove the labels."

Could you specify what it is that you want to have changed? 

Best,

Maya

**Comment by alieden** [comment]
This is really a minor thing. If it's easy to introduce I think a hover over function would be best i.e. no labels but possibility see them (including the equation for the XY prediction interval)? Otherwise just remove the labels. Once again, minor issue that could be left for later.
