### ISSUE TITLE
NCV_X for PCS data adjustment?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#62]
We have noticed that when we switch the process control sample (PCS) we sometimes see a slightly different average (although this is a pool of 50 XY and 50 XX pregnancies) for the new pool. This means that the upper and lower threshold (1,45 SD/NCV) should somehow be adjusted? 

P.S. Before going over to a new batch we run double pcs (new and old) in at least four batches.

Is there someway to address this that wouldn't require a lot of work?

**Comment by mayabrandi** [comment]
Where do you see the different average? Which thresholds? Can you be more specific again :)

**Comment by alieden** [comment]
If you look at the NCV_X pcs values in the statistics tab you can see that the new pcs (pcs-2017-17258) has a slightly higher value than the old (pcs-2017-11500). You can also see that we run both pcs-samples for a nr of batches before swithing to the new. This means that the boundaries +/- 1,45 NCV (compared to expected average for the pcs "batch" over time) becomes incorrect for the new batch.



The pcs is a pool of 100 samples (50 XY/male and 50 XX/female pregnancies) so it will last about 100 batches before we switch. The purpose is that this sample is a process control that should give similar results every run.



Not sure how we should adress this. Perhaps if we could link the boundaries to the pcs sample iD and the average somehow. If this to complicated another option may be that we inform you when we change that pcs and give you the new boundaries but that requires you to change them fairly quickly if ok?



Any other ideas?









________________________________
Från: mayabrandi [notifications@github.com]
Skickat: den 4 oktober 2017 13:40
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] NCV_X for PCS data adjustment? (#62)


Where do you see the different average? Which thresholds? Can you be more specific again :)

**Comment by mayabrandi** [comment]
Okej. Thnx for explaining. I will try to do so, link the average to the sample-id. And show overlapping boundaries while where you run both samples in a batch?

**Comment by mayabrandi** [comment]
@alieden Can you check this out and tell me if you are happy now and I can close the issue?

**Comment by alieden** [comment]
Yes perfect, thank you! Could you please explain a bit what ”marking and positions” is needed for this to work when we switch between pcs batches?

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 10:38
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] NCV_X for PCS data adjustment? (#62)


@alieden<https://github.com/alieden> Can you check this out and tell me if you are happy now and I can close the issue?

**Comment by mayabrandi** [comment]
Just to name the sample consistently all the time. (I have made exception for missmatch in uppercase/lowercase letters. So PCS-123 is interpreted to be the same as pcs-123. This because I you have already made this kind of ”misstake” when entering the sample sheet before. )
