### ISSUE TITLE
Added QC-metric, IndexedReads2Clusters

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#64]
IndexedReads2Clusters should be added as a QC-meric to follow-over time in the statistics tab.

**Comment by mayabrandi** [comment]
Hmm. Cant find a metric with that name. There is only TotalIndexedReads2Clusters, what I can see. And this one is already represented with a plot in the statistics section. I might be miss understanding something..

**Comment by alieden** [comment]
Yes you are correct. Illumina has it as key QC-metric in their presentation from the training course but it’s not present in the reported data (also checked the 2015 files) :)

In other words you can close that down, we have clusters and non excluded sites so should med ok.

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 13:54
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Added QC-metric, IndexedReads2Clusters (#64)


Hmm. Cant find a metric with that name. There is only TotalIndexedReads2Clusters, what I can see. And this one is already represented with a plot in the statistics section. I might be miss understanding something..

**Comment by mayabrandi** [comment]
OK!
