### ISSUE TITLE
Added QC-metric, PerfectMatchTags2Tags

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#65]
PerfectMatchTags2Tags should be added as a QC-meric to follow-over time in the statistics tab.

**Comment by mayabrandi** [comment]
@alieden Can I close this now?

**Comment by alieden** [comment]
Yes!

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 14:18
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Added QC-metric, PerfectMatchTags2Tags (#65)


@alieden<https://github.com/alieden> Can I close this now?
