### ISSUE TITLE
Added QC-metric, Cluster Density

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#66]
Cluster density (flowcell)  should be added as a QC-meric to follow-over time in the statistics tab.

**Comment by mayabrandi** [comment]
Do you know what that field is called in the result files? "Flowcell" or "Clusters" maybe?

**Comment by alieden** [comment]
Clusters

Agne

9 okt. 2017 kl. 12:18 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:


Do you know what that field is called in the result files? "Flowcell" or "Clusters" maybe?

**Comment by mayabrandi** [comment]
@alieden Can I close this now?

**Comment by alieden** [comment]
Yes!

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 14:17
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Added QC-metric, Cluster Density (#66)


@alieden<https://github.com/alieden> Can I close this now?
