### ISSUE TITLE
Added QC-metric, Stdev

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#67]
Stdev for ratio 13, 18 and 21 should be added as QC-metrics to follow-over time in the statistics tab.

**Comment by mayabrandi** [comment]
@alieden Can you confirm that this issue is ready to be closed?

**Comment by alieden** [comment]
Yes, thank you!

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 08:09
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Added QC-metric, Stdev (#67)


@alieden<https://github.com/alieden> Can you confirm that this issue is ready to be closed?
