### ISSUE TITLE
Minor enhancement - Lines missing

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#68]
Sometimes vertical lines (most often only one) are missing in the tables but also in the QC-metric tabs? An example is the batch 1744418_601409. Do you see this too or browser related or so?

**Comment by mayabrandi** [comment]
Hej!

I know Ive seen this before, but now I dont.. Do you still have this problem?

**Comment by mayabrandi** [comment]
Ill close this now. If you see this again, please report it in a new issue
