### ISSUE TITLE
Update regarding QC Metrics and Upper and Lower Boundaries 

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#69]
[GEN-E100.pdf](https://github.com/Clinical-Genomics/NIPT/files/1352501/GEN-E100.pdf)

This is a document with the **updated** QC-metric boundaries (NGS option 1 on page 45) suggested by Illumina for reference. Please note that we for now want to keep the previously set lower boundaries for the ratios (13,18,21) so only change the upper. If it's easier for you that I make separate issues for these, just let me now.

**Comment by mayabrandi** [comment]
Is it only thresholds for the ratios (13,18,21) that you want to change? Or for all QC-metrics?

**Comment by alieden** [comment]
We should check and update all the QC-metric included now and previous. I can go through and make separate issues if this is easier for you?

**Comment by mayabrandi** [comment]
Just to be sure... I should not change the NCV-plots? Only the plots in the statistics section? You dont need to make separate issues. For the 13,18,21 ratios, I use med+stdev?

**Comment by mayabrandi** [comment]
@alieden I believe we are done with this one to now.
