### ISSUE TITLE
Enhancement -Read only account for the NIPT data viewer

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#75]
If possible it would be good if we could get a read only account for the NIPT Data Viewer. This account would be used by our medical doctors that approve the results from each batch. In most cases they will only look at the batch report produced by the technicians but in some cases it would be good if they could also look at the data in more detail (zooming etc). Since the medical doctors are only placed in the fetal department for a couple of weeks at a time and coming back ~5 times/year it would be preferable if they read only users.

**Comment by mayabrandi** [comment]
Should the doctors be able to see all batches and all views for a batch? @alieden

**Comment by mayabrandi** [comment]
I made it possible to be "read only" now. But the user will be able to see everything. Can you give me a email address that I can add, that you can use to see what it is like to be a "read only" user? The new functionality is not in production yet. I want you to test it first. @alieden 

Best,

Maya

**Comment by alieden** [comment]
Yes!

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 30 maj 2018 10:42
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Enhancement -Read only account for the NIPT data viewer (#75)


Should the doctors be able to see all batches and all views for a batch? @alieden<https://github.com/alieden>

**Comment by mayabrandi** [comment]
@alieden You can try the data viewer with a read only account here: https://nipt-stage.scilifelab.se/NIPT/

But you need to give me a email-address that you want to try with!

**Comment by alieden** [comment]
Jag har vb frågan om lämplig epostadress för läkarna, kan finnas en gemensam som dom redan använder för någon funktionsbrevlåda. Återkommer när jag fått besked.

Agne

31 maj 2018 kl. 11:20 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:


@alieden<https://github.com/alieden> You can try the data viewer with a read only account here: https://nipt-stage.scilifelab.se/NIPT/

But you need to give me a email-address that you want to try with!

**Comment by mayabrandi** [comment]
Okej!

Tänkte att jag först skulle lägga in dig som read only så att du skulle kunna testa och se hur det ser ut. Men det kanske inte behövs?

/M

**Comment by alieden** [comment]
Nej det behövs inte:) Är inte på jobbet innan måndag men kan maila lite:)

Agne

31 maj 2018 kl. 12:33 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:

Okej!

Tänkte att jag först skulle lägga in dig som read only så att du skulle kunna testa och se hur det ser ut. Men det kanske inte behövs?

/M

**Comment by mayabrandi** [comment]
The read only functionality is in place in production. Ill close this issue now. You are welcome to open it if there is something you want to change.

/M

**Comment by alieden** [comment]
Hej,

Har nu fått ok på att använda genetik.karolinska@sll.se<mailto:genetik@sll.se> för läkarnas inloggning.

Mvh,

Agne

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 31 maj 2018 12:34
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Enhancement -Read only account for the NIPT data viewer (#75)

Okej!

Tänkte att jag först skulle lägga in dig som read only så att du skulle kunna testa och se hur det ser ut. Men det kanske inte behövs?

/M

**Comment by mayabrandi** [comment]
👍🏻 jobbar inte resten av denna vecka men lägger in det på måndag!

Skickat från min iPhone

**Comment by mayabrandi** [comment]
Hej!

Nej, sorry. Glömde lägga in igår. Har lagt till kontot nu. Vad vill du att användaren ska heta? Vet inte om det framgick, men du är inte begränsad till att bara ha ett "read only" konto. 

Mvh,

Maya

**Comment by alieden** [comment]
Användaren kan väl heta Clinician.

Jag vill förstås gärna ha obegränsade rättigheter till mitt konto, ”god mode” eller så:)

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 12 juni 2018 11:28
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Enhancement -Read only account for the NIPT data viewer (#75)

Hej!

Nej, sorry. Glömde lägga in igår. Har lagt till kontot nu. Vad vill du att användaren ska heta? Vet inte om det framgick, men du är inte begränsad till att bara ha ett "read only" konto.

Mvh,

Maya

**Comment by alieden** [comment]
Nej det räcker med ett.

Agne

12 juni 2018 kl. 13:25 skrev mayabrandi <notifications@github.com<mailto:notifications@github.com>>:

Ja det fattar jag. Men tänkte ifall ni ville ha några fler läkar-konton.

Skickat från min iPhone
