### ISSUE TITLE
Coverage Y vs Coverage X - Enhancement 

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#78]
2. Add a graph showing the coverage of Y vs the coverage of X. This graph should follow the same set up as the NCVY vs NCVX graph with the current batch overlaying the previous included samples etc. The main purposes of this graph are to provide the coverage value for the X-chromosome when we detect X0 samples (for comparison with the fetal fraction) but also to provide additional information when we have an NCD-error. About 0,3% of the analyzed samples are failed due to a NCDY/13/18/21/X error. This means that one of the reference chromosomes used in the NCV calculation is deviating too much. When this occurs, we don’t get a fetal fraction estimate or NCV-values. However, when the sample is a XY-sample we can usually get an idea about the fetal fraction from the CovX and CovY values and relate that to the deviation in coverage we see for the reference chromosome. This will provide information on the likelihood of the aberration being confined to the placenta etc.

**Comment by mayabrandi** [comment]
I close this issue now! You are welcome to reopen it if you want to add anything new.
