### ISSUE TITLE
Altered settings for the reporting of coverage - Enhancement

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#79]
We have discussed when the coverage values (chr1-22 and X and Y (to bee added)) should be visible in the viewer and have agreed that these should only be presented (and included in the report) if there is an aberrant sample (T21 etc) or another QC warning/failure (like an NCD error) present. A normal batch without any flags should not show the coverage values. However, the optimal solution in my mind would be if we could decide ourselves when to view/include coverage by a “button” but I guess that type of function requires more work?

**Comment by mayabrandi** [comment]
Added two different buttons one for include coverage, and one for without coverage. Hope okej.
