### ISSUE TITLE
The NIPT data viewer is unstable

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#8]
The NIPT data viewer is not working properly today. You can save a couple of changes and then you are thrown out? I will also use the ticket system to report this issue.

**Comment by mayabrandi** [comment]
Hi Agne.

Is this happening on a particular batch? What error message do you get? Could you maybe send a screen shot?

Best,

M

**Comment by alieden** [comment]
Hi Maya,

No particular batch, happens all the time.

As previously you just get a message that the webpage can’t be shown, HTTP 500, internt serverfel.

Does it work fine for you if you connect from “the outside” and go between batches etc?

Kr,

Agne



Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 11 oktober 2016 11:13
Till: Clinical-Genomics/NIPT
Kopia: Agne Lieden; Author
Ämne: Re: [Clinical-Genomics/NIPT] The NIPT data viewer is unstable (#8)

Hi Agne.

Is this happening on a particular batch? What error message do you get? Could you maybe send a screen shot?

Best,

M

**Comment by mayabrandi** [comment]
I have the same issue now. We are looking in to it and will get back to you as soon as its fixed
