### ISSUE TITLE
Log in for labtechs via one account - Enhancement

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#80]
For simplicity we want the labtechs to use one account when they log into the viewer. We will be able to trace who has added a certain batch to the database through our LIMS anyway. 

Could we use our previously set up account nipt.karolinska@gmail.com? Or even better, could we connect the same address as for the results delivery, nipt.karolinska@sll.se?

**Comment by mayabrandi** [comment]
I added nipt.karolinska@sll.se. Try and see if it works.

**Comment by alieden** [comment]
Jäpp, funkar!

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 26 april 2018 15:43
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Log in for labtechs via one account - Enhancement (#80)


I added nipt.karolinska@sll.se<mailto:nipt.karolinska@sll.se>. Try and see if it works.
