### ISSUE TITLE
Sample list non-functional

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/NIPT#87]
Hello!
When I click Sample List it says "502 Bad Gateway nginx". Hope this can be fixed!
Ellika

**Comment by mayabrandi** [comment]
Ill look in to it!


/M

**Comment by mayabrandi** [comment]
Hi Ellika!

The problem with ”bad gate way” is now fixed. But as the database has grown the samples page takes very long to load. I will make a separate issue for fixing that. Unfortunately I’m a bit overwhelmed with work for the moment so it won’t be fixed directly. Meanwhile I recommend you just keep the samples tab open, once you have opened it. Once it’s been loaded its pretty fast.


Hope you’re fine with that.

Best,

Maya
