### ISSUE TITLE
Possible bug in sample search function?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#95]
I had some problems using the new search function regarding a previously failed sample (2016-25256). I get no match in the database although the batch and the sample is there (found through batch search)? The same is true for the new blood sample from the same patient that also failed (2017-01041).

**Comment by mayabrandi** [comment]
Yes. That must be  bug. Ill look into it!

/M

**Comment by mayabrandi** [comment]
Fixed!
