### ISSUE TITLE
Unable to download NIPT db - bug?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#98]
The request to download the NIPT database is "timed out"?

Det går inte att visa den här sidan

•Kontrollera att webbadressen https://nipt.scilifelab.se  är korrekt.
•Sök efter sidan med sökmotorn.
•Uppdatera sidan om några minuter.

**Comment by mayabrandi** [comment]
Hej! 

Jag var på semester förra veckan. Går det bra att komma in nu? Jag har inga problem att komma in.

mvh,

Maya

**Comment by alieden** [comment]
Nu fungerade det att ladda ner!

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 25 juni 2018 07:30
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Unable to download NIPT db - bug? (#98)

Hej!

Jag var på semester förra veckan. Går det bra att komma in nu? Jag har inga problem att komma in.

mvh,

Maya
